# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: ActionCI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: write
      packages: write 
    steps:
      # Git checkout
      - uses: actions/checkout@v2
        
      # Setup Java
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RaphaelVRossi_commons

      - name: Maven version
          id: bump
          uses: raphaelvrossi/action-maven-bump-version@v1.2
          with:
            git-token: ${{ secrets.GIT_TOKEN }}

      - name: Publish package
        run: echo ${{ steps.bump.outputs.old-version }} ; echo ${{ steps.bump.outputs.version }} ;  echo ${{ steps.bump.outputs.updated }} ;

      - name: AAAA
        if: ${{ steps.bump.outputs.updated }} == 1
        run: echo 'RUNNNNNN'

      # Maven Publish
#       - name: Publish package
#         run: mvn --batch-mode deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
