# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      # Git checkout
      - uses: actions/checkout@v2
      
      # Setup Java
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      # Maven bump version
      - name: Maven Version Bump Action
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
      
      # Maven Publish
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
